blog_app/urls.py
from django.urls import path
from . import views



app_name='blog_app'


urlpatterns = [
    path('', views.posts, name='posts'),
    path('post/create/', views.create_post, name='post_create'),
    path('category_posts/<str:slug>', views.category_posts, name='category_posts'),
    path('<str:slug>/', views.PostsDetailsView, name='post_details'),
    path('<str:slug>/update', views.post_update, name='post_update'),
    path('<str:slug>/delete', views.post_delete, name='post_delete'),
    path('<str:slug>/like_or_unlike/', views.like_or_unlike, name='like_or_unlike'),
    path('<str:slug>/<int:id>/comment_update', views.comment_update, name='comment_update'),
    path('<str:slug>/<int:id>/comment_delete', views.comment_delete , name='comment_delete'),
    path('<str:slug>/<int:id>/reply_create'  , views.reply_create , name='reply_create'),
    path('<str:slug>/<int:id>/<int:pk>/reply_to_reply_create'  , views.reply_to_reply_create , name='reply_to_reply_create'),
        #post_deatils #comment #reply
    
    #slug must be the last path in case i have an url matchs with slug the browser will go to the url not the slug
    
    

]

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')), # to create accounts following my conditions
    path('admin/', admin.site.urls, name='admin'),
    path('destinations/', include('destination_app.urls',namespace='destination')),
    path('blogs/', include('blog_app.urls',namespace='blog')),
    path('martor/', include('martor.urls')),                    # text editor 
    path('oauth/', include('social_django.urls', namespace='social')), # for social login
    path('ratings/', include('star_ratings.urls', namespace='ratings')), # stars rating
    path('chat/', include('chat.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# debug_toolbar settings:

if settings.DEBUG:
    import debug_toolbar
    urlpatterns+= path('__debug__/', include(debug_toolbar.urls)),

blog_app/models.py
from accounts.models import Profile
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from martor.models import MartorField 



class Post(models.Model):
    title = models.CharField(max_length=100, unique= True)
    description = models.TextField()
    published_at = models.DateTimeField(auto_now_add=True)
    author= models.ForeignKey(User, on_delete=models.CASCADE)   # it is better to be related to Profile to acsess more info about the user  (next time xD)
    categories = models.ManyToManyField('Category', blank=False, related_name="posts")
    post_cover = models.ImageField(upload_to='Posts')                   #related_name to get the posts of this category
    slug= models.SlugField(blank=True, null=True, unique=True)
    likes= models.ManyToManyField(User, blank=True, related_name="likes")
    content = MartorField()               # must be the last to write down to it hints
                                                                   


    def save(self,*args, **kwargs):              #overriding save method 
        self.slug= slugify(self.title)           #create a slug
        super(Post,self).save(*args,**kwargs)

    def __str__(self):
        return self.title


    @property
    def get_comments(self):                  # property to relate between post and comments so comments appear only in post page and I can call get_comments as a field in Post. Also, Must also give related_name in comment class
        
        return self.comments.filter(reply__isnull=True,).order_by('-commented_at')        #for more https://stackoverflow.com/questions/58558989/what-does-djangos-property-do
                                    # filter the comments only not replies
    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()

    @property                                # property so if i delete post i delete its views
    def views_count(self):                   # to recored views count
        return PostViews.objects.filter(post=self).count()
    


class Comment(models.Model):
    commented_at = models.DateTimeField(auto_now_add=True)
    content= MartorField()
    replier= models.ForeignKey(Profile, on_delete=models.CASCADE, default=1)
    post=models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    reply=models.ForeignKey('Comment', on_delete=models.CASCADE, related_name="replies", null=True, blank=True,)
      # recursive relationship for replies 


class PostViews(models.Model):                              # to recored views count
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    IPAddres= models.GenericIPAddressField(default="45.243.82.162")
    
    def __str__(self):
        return '{0}'.format(self.IPAddres)



class Category(models.Model):
    title = models.CharField(max_length=20)
    slug  = models.SlugField(blank=True, null=True, unique=True)

    def save(self,*args, **kwargs):              #overriding save method 
        self.slug= slugify(self.title)           #create a slug
        super(Category,self).save(*args,**kwargs)
  
    def __str__(self):
        return self.title


blog_app/forms.py
from django import forms
from .models import Category, Post, Comment
from martor.fields import MartorFormField


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','description','post_cover','categories','content')
        content = MartorFormField()
       

    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),            # give many to many field user friendly shape
        widget=forms.CheckboxSelectMultiple
    )

        

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)
        content = MartorFormField()



blog_app/views.py
from accounts.models import Profile
from blog_app.forms import CommentForm, PostForm
from django.db.models import Q, Count
from blog_app.models import Category, Comment, Post, PostViews
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required


'''
class PostsView(ListView):
    model = Post
    #queryset = Post.objects.all()
    template_name = 'post/posts.html'
    context_object_name ='posts' 
    paginate_by = 1

'''


def posts(request):
    posts = Post.objects.all()
    query = request.GET.get('q')                #the search text form <input name="" />HTML
    if query:
        posts = posts.filter(
            Q(title__icontains=query) |             # filter with containing in title, description or content 
            Q(description__icontains=query) |       # contains vs icontains where i stands for insensitive
            Q(content__icontains=query)
        ).distinct()                                # don't repeat the results

    p = Paginator(posts, 2)#num of items per page
    page_number = request.GET.get('page')
    try:
        page_obj = p.page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)                  #if page number is not intger get the first page
    except EmptyPage:
        page_obj = p.page(p.num_pages)        #if page is empty get the last page

    context={
        'posts'         : page_obj,
        "query"         : query,
              
    }
    return  render(request, 'post/posts.html',context)



def PostsDetailsView(request,slug,):
    page_title="Post Content"
    post_details=Post.objects.get(slug=slug)
    replies=Comment.objects.filter(reply__isnull=False, )       # filter replies only not comments
    latest=Post.objects.all().order_by('-published_at')[0:3]  # the latest posts
    categories = Post.objects.values('categories__title','categories__slug').annotate(qcount=Count('categories')).order_by('-qcount') # To show how many posts per category and order_by the highest category in posts count (DESC)
                                            #↓
            #must be written like this because it is many_too_many field returns with ids not titles                   

    form = CommentForm(request.POST or None, request.FILES or None)
    if request.method == "POST":
        if form.is_valid():
            profile=Profile.objects.get(user=request.user)  # if i write it before form is valid it block anynomys users from entering the page
            form.instance.replier = profile        # check if the form is vaild give it the the logged in user profile
            form.instance.post = post_details      # and the post of the comment (both are model fields)
            form.save()
            return redirect(reverse('blog:post_details', args=(slug,))) # the way to redirect slug

    
    def get_client_ip(request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')      #to get IPAdress to count the post views
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

                   # to record  one view only per user for every post using his IPAdress
    PostViews.objects.get_or_create(IPAddres= get_client_ip(request) , post=post_details)
  
    context={
        'latest_posts' : latest,
        'post_details' : post_details,
        'categories'   : categories,
        'comment_form' : form,
        'replies'      : replies,
        'page_title'   : page_title,
        }
    return  render(request, 'post/post_details.html',context)




@login_required 
def create_post(request):
    page_title= "Create Post"
    form = PostForm(request.POST or None, request.FILES or None)
    if request.method == "POST":
        if form.is_valid():
            myfrom=form.save(commit=False)
            myfrom.author = request.user
            myfrom.save()
            form.save_m2m()                 # save many 2 many field must be like that
            return redirect(reverse('blog:posts'))
        else:
            form = PostForm()

    context={
        'create_or_update_post_form' : form,
        'page_title'                 : page_title,
    }
    return render(request, 'post/post_create_or_update.html',context)



@login_required 
def post_update(request,slug):                  #the same view and template create_post with minor change "instance=post_details" 
    page_title= "Edit Post"
    post_details=Post.objects.get(slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=post_details) # use "instance=" to give the form the current data in the form
    if request.method == "POST":
        if form.is_valid():
            myfrom=form.save(commit=False)
            myfrom.save()
            form.save_m2m()                 # save many 2 many field must be like that
            return redirect(reverse('blog:post_details', args=(slug,)))  # the way to redirect slug
        else:
            form = PostForm()

    context={
        'create_or_update_post_form' : form,
        'page_title'                 : page_title,
    }
    return render(request, 'post/post_create_or_update.html', context)     # different urls for the same html page



@login_required 
def post_delete(request,slug):
    post_details=Post.objects.get(slug=slug)
    if request.method=="POST":
        post_details.delete()
        return redirect(reverse('blog:posts'))
    return render(request,'post/post_details.html',)



@login_required
def comment_update(request, slug, id):
    comment=Comment.objects.get(id=id)        
    form = CommentForm(request.POST or None, request.FILES or None, instance=comment)
    if request.method == "POST":
        if form.is_valid(): 
            form.save()
            return redirect(reverse('blog:post_details', args=(slug,))) # the way to redirect slug
        else:
            form = CommentForm()

    context={
        'comment_update_form' : form,
        }
    return  render(request, 'post/comment_update.html',context)


@login_required
def comment_delete(request, slug, id):
    comment=Comment.objects.get(id=id)
    if request.method == "POST":
        comment.delete()
        return redirect(reverse('blog:post_details', args=(slug,))) # the way to redirect slug
    return render(request,'post/post_details.html',)



@login_required
def reply_create(request, slug, id,):   #create first reply
    page_title="Create reply"
    post_details=Post.objects.get(slug=slug)
    reply_to=Comment.objects.get(id=id)     #reply to comment
    form=CommentForm(request.POST or None, request.FILES or None, initial={'content':'@[{0}]'.format(reply_to.replier)})
    if request.method=='POST':                                    #to mention the replied_to person in the reply (facebook like)
        if form.is_valid:
            profile=Profile.objects.get(user=request.user)
            form.instance.replier=profile
            form.instance.post=post_details
            form.instance.reply=reply_to
            form.save()
            return redirect(reverse('blog:post_details', args=(slug,))) # the way to redirect slug
        else:
            form = CommentForm()

    context={
        'reply_create_form' : form,
        'page_title'        :page_title,
        }
    return  render(request, 'post/reply_create.html',context)


@login_required
def reply_to_reply_create(request, slug, id, pk):   #create the nested replies
    page_title="Create reply"
    post_details=Post.objects.get(slug=slug)
    reply_to=Comment.objects.get(id=id)        #reply to comment, to show it as the first reply down to comment (facebook like)
    reply_to_reply=Comment.objects.get(id=pk)  #the mentioned reply  
    form=CommentForm(request.POST or None, request.FILES or None, initial={'content':'@[{0}]'.format(reply_to_reply.replier)})
    if request.method=='POST':                                    #to mention the replied_to person in the reply (facebook like)
        if form.is_valid:
            profile=Profile.objects.get(user=request.user)
            form.instance.replier=profile
            form.instance.post=post_details
            form.instance.reply=reply_to
            form.save()
            
            return redirect(reverse('blog:post_details', args=(slug,))) # the way to redirect slug
        else:
            form = CommentForm()
    
    context={
        'reply_create_form' : form,
        'page_title'        :page_title,
        }
    return  render(request, 'post/reply_create.html',context)


@login_required
def like_or_unlike(request,slug):
    post = Post.objects.get(slug=slug)

    if request.user in post.likes.all():               # unlike or like depending if the user liked or not
        post.likes.remove(request.user)
        
        return redirect(reverse('blog:post_details', args=(slug,)))
    else:
        post.likes.add(request.user)

        return redirect(reverse('blog:post_details', args=(slug,)))



def category_posts(request, slug):
    page_title="Post Category"
    category= Category.objects.get(slug=slug)
    category_posts=category.posts.all()         #posts is a related name in models/Post/categories

    p = Paginator(category_posts, 1)#num of items per page
    page_number = request.GET.get('page')
    #page_obj = p.get_page(page_number)

    try:
        page_obj = p.page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)                  #if page number is not intger get the first page
    except EmptyPage:

blog_app/templates/post/comment_update.html
{% extends "base.html" %}
{%load static%}
{% load bootstrap4 %}
{%block body%}

    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Edit Comment</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span>  <span>{{page_title}} <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>
          <section class="ftco-section ftco-no-pt ftco-no-pb">
            <div class="comment-form-wrap pt-5 ">
                <h3 class="mb-5 offset-1">Edit Comment</h3>
                <form action="" method="POST" class="p-5 bg-light" enctype="multipart/form-data">
                <div class="form-group">
                    
                    {% csrf_token %}
                    {% bootstrap_form comment_update_form %}
                    
                  </div>
                  <div class="form-group">
                    <input type="submit" value="Post" class="btn py-3 px-4 btn-primary">
                  </div>

            </section>
{% endblock %}

blog_app/templates/post/post_details.html
{% extends "base.html" %}
{%load static%}
{% load bootstrap4 %}
{% load martortags %}
{%block body%}

    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Blog Details</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="blog.html">Blog <i class="ion-ios-arrow-forward"></i></a></span> <span>{{page_title}} <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section ftco-no-pt ftco-no-pb">

  <style>
    .col-lg-8 img{

        width: 100%;                  
    }
  </style>                         <!--to make sure that images in content are suitable for the page-->
      <div class="container">
        <div class="row">
          <div class="col-lg-8 order-md-last ftco-animate py-md-5 mt-md-5">
            <h2 class="mb-3">{{post_details.title}}</h2>
            {{post_details.content| safe_markdown}}  <!--to create a content. Using safe to don't show html code-->

            {% ifequal post_details.author request.user %}        <!--if the author of the post equals the the user who opened the page-->
            
            <a href="{% url 'blog:post_update' post_details.slug%}" class="reply">Edit</a> <br>

            <form action="{% url 'blog:post_delete' post_details.slug%}" 
                method="POST" style="display: inline;" onsubmit="window.mytest()">
                {% csrf_token %}                                                    <!-- Form to confirm the deletion of the post with Ajax ↓ -->
                <input type="hidden" name="album_id"                                
                    value="{{post_details.title}}" />
                <button type="submit" class="btn btn-default btn-sm">
                    <span >Delete</span>
                </button>
            </form> 
          <script type="text/javascript">window.mytest = function() { var isValid = confirm('Are you sure ?');if (!isValid) { event.preventDefault(); }}</script>
            {% endifequal %}


            <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
              {% for category in categories %}
                <a href="{% url 'blog:category_posts' category.categories__slug %}" class="tag-cloud-link">{{category.categories__title}}</a>
                                                                                                                          <!--↓-->
                                                                             <!--must be written like this because it is many_too_many field returns with ids not titles-->            
                {% endfor %}
              </div>
            </div>
            
            <div class="about-author d-flex p-4 bg-light">
              <div class="desc">
                <h3>Author: {{post_details.author}}</h3>

                {% if request.user in post_details.likes.all %} <!--unlike or like depending if the user liked or not-->

                <a href= "{% url 'blog:like_or_unlike' post_details.slug %}" class="unlike">unlike</a>
                {% else %}
                <a href= "{% url 'blog:like_or_unlike' post_details.slug %}" class="like">like</a>
                {% endif %}
                <h6>likes: {{post_details.likes.count}}</h6>
              </div>
            </div>



            <div class="pt-5 mt-5">
              <h3 class="mb-5">{{post_details.comment_count}} Comments</h3>
              {% for comment in post_details.get_comments %}                  <!--first loop (comments)-->
              <ul class="comment-list">                                       <!-- ro create the first reply-->
                <li class="comment">
                  <div class="vcard bio">

                  {% if comment.replier.cover_image %}    <!--if the user has profile pic-->
                    <img src={{comment.replier.cover_image.url}} alt="">
                  {% else %}
                    <img src="{% static 'images/person_2.jpg' %}" alt="">
                  {% endif %}
                  </div>
                  <div class="comment-body">
                    <h3>{{comment.replier.user.username}}</h3>
                    <div class="meta">{{comment.commented_at|timesince}} ago</div>
                    <p>{{comment.content|safe_markdown}}</p>

                    
                    
                    

                    {% ifequal comment.replier.user request.user %}        <!--if the author of the comment equals the the user who opened the page then they can delete and edit-->
                    <a href="{% url 'blog:comment_update' post_details.slug comment.id %}" class="reply">Edit</a></p>

                    <form action="{% url 'blog:comment_delete' post_details.slug comment.id %}" 
                      method="POST" style="display: inline;" onsubmit="window.mytest()">
                      {% csrf_token %}                                                    <!-- Form to confirm the deletion of the post with Ajax ↓ -->
                      <input type="hidden" name="album_id"                                
                          value="{{post_details.title}}" />
                      <button type="submit" class="btn btn-default btn-sm">
                          <span >Delete</span>
                      </button>
                    </form> 
                    <script type="text/javascript">window.mytest = function() { var isValid = confirm('Are you sure ?');if (!isValid) { event.preventDefault(); }}</script>
                    
                    {% else %} <!--don't show reply button to the user of request if he is the owner of the comment-->
                    <p><a href="{% url 'blog:reply_create' post_details.slug comment.id %}" class="reply">Reply</a>
                    {%endifequal%}


                  </div>
                {% for reply in replies %}          <!--second loop (replies) tp create more replies-->       
                  {% ifequal reply.reply comment %} <!--if reply_field(the reccursive field) equals the current comment-->
                 
                    
                  <ul class="children">
                    <li class="comment">
                      <div class="vcard bio">
                      {% if reply.replier.cover_image %}
                        <img src="{{reply.replier.cover_image.url}}" alt="">
                      {% else %}
                        <img src="{% static 'images/person_2.jpg' %}" alt="">
                      {% endif %}
                      </div>
                      <div class="comment-body">
                        <h3>{{reply.replier}}</h3>
                        <div class="meta">{{reply.commented_at|timesince}} ago</div>
                        <p>{{reply.content|safe_markdown|truncatechars_html:50}}</p>

                    
                    {% ifequal reply.replier.user request.user %}         <!--if the author of the comment equals the the user who opened the page then they can delete and edit-->
                    <a href="{% url 'blog:comment_update' post_details.slug reply.id %}" class="reply">Edit</a></p>

                    <form action="{% url 'blog:comment_delete' post_details.slug reply.id %}" 
                      method="POST" style="display: inline;" onsubmit="window.mytest()">
                      {% csrf_token %}                                                    <!-- Form to confirm the deletion of the post with Ajax ↓ -->
                      <input type="hidden" name="album_id"                                
                          value="{{post_details.title}}" />
                      <button type="submit" class="btn btn-default btn-sm">
                          <span >Delete</span>
                      </button>
                    </form> 
                    <script type="text/javascript">window.mytest = function() { var isValid = confirm('Are you sure ?');if (!isValid) { event.preventDefault(); }}</script>
                    
                    {% else %} <!--don't show reply button to the user of request if he is the owner of the reply-->
                    <p><a href="{% url 'blog:reply_to_reply_create' post_details.slug comment.id reply.id%}" class="reply">Reply</a>
                               <!--the comment.id to reply to this comment--> <!--the reply.id to mention the replied-to person-->
                    {%endifequal%}
                      </div>
                    </li>
                  </ul>
                </li>

                {% endifequal %}
              {% endfor %}  <!-- replies for-loop ( second nested loop) --> 

              </ul>
              {% endfor %}  <!-- comments for-loop (first)--> 
              <!-- END comment-list --> 

              <div class="comment-form-wrap pt-5">
              {% if user.is_authenticated %}
                <h3 class="mb-5">Leave a comment</h3>
                <form action="" method="POST" class="p-5 bg-light" enctype="multipart/form-data">
                
                  <div class="form-group">
                    
                    {% csrf_token %}
                    {% bootstrap_form comment_form %}
                    
                  </div>
                  <div class="form-group">
                    <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                  </div>
                {% else %}
                <p class="no-comments-allowed">
			            Please <a href="{% url 'login'%}" title="Special:UserLogin">log in</a> to post a comment on this post.		</p>
                {% endif %}
                </form>
              </div>
            </div>
          
          </div> <!-- .col-md-8 -->
          <div class="col-lg-4 sidebar ftco-animate bg-light py-md-5">
            <div class="sidebar-box pt-md-5">                                 <!-- search form -->
              <form action="{% url 'blog:posts' %}" class="search-form">
                <div class="form-group">
                  <span class="icon icon-search"></span>
                  <input type="text" class="form-control" name="q" placeholder="Type a keyword and hit enter"> 
                </div>
              </form>
            </div>
            <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3>Categories</h3>
                
                {% for category in categories %}
                <li><a href="{% url 'blog:category_posts' category.categories__slug %}">{{category.categories__title}} <span>({{category.qcount}})</span></a></li>
                                                                                                      <!--↓-->
                                                                                            <!--must be written like this because it is many_too_many field returns with ids not titles-->
                {% endfor %}

              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Recent Blogs</h3>
              {% for latest in latest_posts %}
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url({{latest.post_cover.url}});"></a>
                <div class="text">
                  <h3 class="heading"><a href="{% url 'blog:post_details' latest.slug%}">{{latest}}</a></h3>
                  <div class="meta">
                    <div><a href="{% url 'blog:post_details' latest.slug%}"><span class="icon-calendar"></span> {{latest.published_at|date:'d M Y'}}</a></div>
                    <div><a href="{% url 'blog:post_details' latest.slug%}"><span class="icon-person"></span> {{latest.author}}</a></div>
                    <div><a href="{% url 'blog:post_details' latest.slug%}"><span class="icon-chat"></span> {{latest.comment_count}}</a></div>
                    <div><a href="{% url 'blog:post_details' latest.slug%}">{{latest.views_count}} Views</a></div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Paragraph</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
            </div>
          </div>

        </div>
      </div>
    </section> <!-- .section -->
    
    {% endblock %}