chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

destination_app/urls.py
from django.urls import include , path
from . import views

app_name='destination_app'

urlpatterns = [
    path('', views.DestinationsView, name='destinations'),

    path('<str:slug>', views.DestinationDetailsView, name='destination_details'),  #must be the last path in case i have an url matchs with slug the browser will go to the url not the slug
    
    
    


]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')), # to create accounts following my conditions
    path('admin/', admin.site.urls, name='admin'),
    path('destinations/', include('destination_app.urls',namespace='destination')),
    path('blogs/', include('blog_app.urls',namespace='blog')),
    path('martor/', include('martor.urls')),                    # text editor 
    path('oauth/', include('social_django.urls', namespace='social')), # for social login
    path('ratings/', include('star_ratings.urls', namespace='ratings')), # stars rating
    path('chat/', include('chat.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# debug_toolbar settings:

if settings.DEBUG:
    import debug_toolbar
    urlpatterns+= path('__debug__/', include(debug_toolbar.urls)),

destination_app/models.py
from django.db import models
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField      # changes in settings
from django.utils.text import slugify

from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating

# Create your models here.

distincit_with_choices=[
              #db name        #UI name
            ('near_beach', 'Near Beach'),
            ('near_mountain','Near Mountain'),
]


class Destination(models.Model) :
    title = models.CharField(max_length=100,)
    duration= models.PositiveSmallIntegerField(null=False)
    image= models.ImageField(upload_to='Destinations')
    description = models.TextField(max_length=1000)

    rooms = models.PositiveSmallIntegerField(null=False)
    bathrooms= models.PositiveSmallIntegerField(null=False)
    distinct_with = models.CharField(max_length=100, choices=distincit_with_choices, blank=True)

    price=models.IntegerField(null=False)
    website=models.URLField(null=True)
    slug= models.SlugField(blank=True, null=True)
    ratings = GenericRelation(Rating, related_query_name='ratings') # to query by ratings

    check_in_date=models.DateField()
    check_out_date=models.DateField()
    published_at= models.DateTimeField(auto_now=True)
    company = models.CharField(max_length=100, null=True)

    city=models.CharField(max_length=100, null=False, blank=False)
    country = CountryField(null=False , blank=False, db_index=True,   #package
    countries_flag_url='flags/{code}.gif')                         #to show flags #check out settings, base.html, static files(flags), template 
    phone_number=PhoneNumberField(null=False , blank=False)        #package  #check out settings


    def save(self,*args, **kwargs):              #overriding save method in admin page
       self.slug= slugify(self.title)           #create a slug
       super(Destination,self).save(*args,**kwargs)


    def __str__(self):
         return self.title


class DestinationGallary(models.Model):     # to show destination photos in details # check out admin.py
    destination = models.ForeignKey(Destination, default=None, on_delete=models.CASCADE)
    images = models.ImageField(upload_to = 'Destination_gallary')

    def __str__(self):
         return '{0}'.format(self.images)


class Booking(models.Model):
    full_name=models.CharField(max_length=50, default="", null=False , blank=False)
    email=models.EmailField( max_length=254, default="", null=False , blank=False)
    phone_number=PhoneNumberField(null=False , blank=False, default='' )
    destination=models.ForeignKey(Destination, on_delete=models.CASCADE, default="", null=False , blank=False)
    country = CountryField(null=False , blank=False, db_index=True,   #package
    default="", countries_flag_url='flags/{code}.gif')
    check_in_date=models.DateField( null=False , blank=False)
    check_out_date=models.DateField( null=False , blank=False)

    def __str__(self):
         return '{0}'.format(self.destination)
         
   

destination_app/forms.py
from django import forms
from . models import Booking




class BookingForm(forms.ModelForm):  
    class Meta:
        model= Booking
        fields= ('check_in_date','check_out_date')
        widgets = {
            'check_in_date': forms.DateInput(attrs={'type': 'date'}),
            'check_out_date': forms.DateInput(attrs={'type': 'date'}),
        }
        

destination_app/views.py
from destination_app.forms import BookingForm
from django.shortcuts import redirect, render
from destination_app.models import  Booking, Destination, DestinationGallary
from accounts.models import Profile
from django.db.models import Count
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.urls import reverse
from destination_app.filters import DestinationFilter


# Create your views here.

'''
class DestinationsView(ListView):
    model = Destination
    #queryset = Destination.objects.all()
    template_name = 'destination/destinations.html'
    #context_object_name ='destinations' 
    paginate_by = 3

    
'''

def DestinationsView(request):
    all = Destination.objects.all().order_by('price')
    top_countries = Destination.objects.values('country').annotate(qcount=Count('country')).order_by('-qcount')[:4]
                    # group_by countries which are categories for destinations. To show how many destinations per country and order_by the highest country in destinations count (DESC)

    myfilter=DestinationFilter(request.GET,queryset=all)
    filtered_destinations=myfilter.qs                   # this line is a must for pagination  

    p = Paginator(filtered_destinations, 3)#num of items per page
    page_number = request.GET.get('page')
    #page_obj = p.get_page(page_number)

    try:
        page_obj = p.page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)                  #if page number is not intger get the first page
    except EmptyPage:
        page_obj = p.page(p.num_pages)        #if page is empty get the last page

    context ={
            'destinations' :page_obj,
            'top_countries' :top_countries,
            'myfilter'      :myfilter,
            }

    return render(request, 'destination/destinations.html',context)


def DestinationDetailsView(request, slug):
    destination_details=Destination.objects.get(slug=slug)        
    photos = DestinationGallary.objects.filter(destination=destination_details) # to show destination gallary
                                               #foreignkey field     #queryset 
    highly_rated_destinations= Destination.objects.filter(ratings__isnull=False).order_by('ratings__average')[:3]

    form=BookingForm(request.POST or None)
    if request.method=='POST' and form.is_valid():
        if not Booking.objects.get(full_name= request.user):    # if not user already booked in the travel 
            profile=Profile.objects.get(user=request.user)
            form.instance.full_name=profile
            form.instance.email= profile.user.email
            form.instance.phone_number=profile.phone_number
            form.instance.country=profile.country
            form.instance.destination=destination_details
            form.save()
        return redirect(reverse('destination:destination_details', args=(slug,)))


    context={
         'destination_details' : destination_details,
         'photos' : photos,
         'bookingform' : form,
         'highly_rated_destinations' : highly_rated_destinations,
         }
    return render(request,'destination/destination_details.html',context)



destination_app/templates/destination/destination_details.html
{%extends "base.html"%}
{%load static%}
{% load bootstrap4 %}
{% load countries %}
{% load ratings %}
{%block body%}


 
    
    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({%static 'images/bg_1.jpg'%});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Destination Details</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="{% url 'destination:destinations'%}">Destinations <i class="ion-ios-arrow-forward"></i></a></span> <span>Destinations Details <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section ftco-no-pt ftco-no-pb">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 order-md-last ftco-animate py-md-5 mt-md-5">
            <h2 class="mb-3">{{destination_details}}</h2>
            <p>{{destination_details.description}}</p>
              <p>
              {% for photo in photos %}
              
              <img src="{{photo.images.url}}" alt="" class="img-fluid">
              {% endfor %}
            </p>
            <p>Molestiae cupiditate inventore animi, maxime sapiente optio, illo est nemo veritatis repellat sunt doloribus nesciunt! Minima laborum magni reiciendis qui voluptate quisquam voluptatem soluta illo eum ullam incidunt rem assumenda eveniet eaque sequi deleniti tenetur dolore amet fugit perspiciatis ipsa, odit. Nesciunt dolor minima esse vero ut ea, repudiandae suscipit!</p>
            <h2 class="mb-3 mt-5">Further Details</h2>
            <p>Temporibus ad error suscipit exercitationem hic molestiae totam obcaecati rerum, eius aut, in. Exercitationem atque quidem tempora maiores ex architecto voluptatum aut officia doloremque. Error dolore voluptas, omnis molestias odio dignissimos culpa ex earum nisi consequatur quos odit quasi repellat qui officiis reiciendis incidunt hic non? Debitis commodi aut, adipisci.</p>

            <p>
              <img src="{{destination_details.image.url}}" alt="" class="img-fluid">
            </p>

            <p>Quisquam esse aliquam fuga distinctio, quidem delectus veritatis reiciendis. Nihil explicabo quod, est eos ipsum. Unde aut non tenetur tempore, nisi culpa voluptate maiores officiis quis vel ab consectetur suscipit veritatis nulla quos quia aspernatur perferendis, libero sint. Error, velit, porro. Deserunt minus, quibusdam iste enim veniam, modi rem maiores.</p>
            <p>Odit voluptatibus, eveniet vel nihil cum ullam dolores laborum, quo velit commodi rerum eum quidem pariatur! Quia fuga iste tenetur, ipsa vel nisi in dolorum consequatur, veritatis porro explicabo soluta commodi libero voluptatem similique id quidem? Blanditiis voluptates aperiam non magni. Reprehenderit nobis odit inventore, quia laboriosam harum excepturi ea.</p>
            <p>Adipisci vero culpa, eius nobis soluta. Dolore, maxime ullam ipsam quidem, dolor distinctio similique asperiores voluptas enim, exercitationem ratione aut adipisci modi quod quibusdam iusto, voluptates beatae iure nemo itaque laborum. Consequuntur et pariatur totam fuga eligendi vero dolorum provident. Voluptatibus, veritatis. Beatae numquam nam ab voluptatibus culpa, tenetur recusandae!</p>
            <p>Voluptas dolores dignissimos dolorum temporibus, autem aliquam ducimus at officia adipisci quasi nemo a perspiciatis provident magni laboriosam repudiandae iure iusto commodi debitis est blanditiis alias laborum sint dolore. Dolores, iure, reprehenderit. Error provident, pariatur cupiditate soluta doloremque aut ratione. Harum voluptates mollitia illo minus praesentium, rerum ipsa debitis, inventore?</p>
            
            <div class="col-md-4 mt-sm-30">
						<h3 class="mb-20">Travel Features</h3>
						<div class="">
							<ul class="unordered-list">
								<li>Duration: {{destination_details.duration}} Days</li>
								<li>Bedrooms: {{destination_details.rooms}} Room(s)</li>
								<li>Bathrooms: {{destination_details.bathrooms}} Room(s)</li>
                <li>Distinct with: {{destination_details.distinct_with}}</li>
                <li>Price: {{destination_details.price}} $/Day</li>
                <li>In {{destination_details.city}}</li>
							</ul>
						</div>
					</div>
                  {% ratings destination_details%}    <!--show rating tag-->

            <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
                <a href="#" class="tag-cloud-link">Life</a>
                <a href="#" class="tag-cloud-link">Sport</a>
                <a href="#" class="tag-cloud-link">Tech</a>
                <a href="#" class="tag-cloud-link">Travel</a>
              </div>
            </div>



            <div class="about-author d-flex p-4 bg-light">
              <div class="bio mr-5">
                <img src="images/person_1.jpg" alt="Image placeholder" class="img-fluid mb-4">
              </div>
              <div class="desc">
                <h3>George Washington</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
              </div>
            </div>


            <div class="pt-5 mt-5">
              <h3 class="mb-5">6 Comments</h3>
              <ul class="comment-list">
                <li class="comment">
                  <div class="vcard bio">
                    <img src="images/person_1.jpg" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>John Doe</h3>
                    <div class="meta">October 03, 2018 at 2:21pm</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                    <p><a href="#" class="reply">Reply</a></p>
                  </div>
                </li>

                <li class="comment">
                  <div class="vcard bio">
                    <img src="images/person_1.jpg" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>John Doe</h3>
                    <div class="meta">October 03, 2018 at 2:21pm</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                    <p><a href="#" class="reply">Reply</a></p>
                  </div>

                  <ul class="children">
                    <li class="comment">
                      <div class="vcard bio">
                        <img src="images/person_1.jpg" alt="Image placeholder">
                      </div>
                      <div class="comment-body">
                        <h3>John Doe</h3>
                        <div class="meta">October 03, 2018 at 2:21pm</div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                        <p><a href="#" class="reply">Reply</a></p>
                      </div>


                      <ul class="children">
                        <li class="comment">
                          <div class="vcard bio">
                            <img src="images/person_1.jpg" alt="Image placeholder">
                          </div>
                          <div class="comment-body">
                            <h3>John Doe</h3>
                            <div class="meta">October 03, 2018 at 2:21pm</div>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                            <p><a href="#" class="reply">Reply</a></p>
                          </div>

                            <ul class="children">
                              <li class="comment">
                                <div class="vcard bio">
                                  <img src="images/person_1.jpg" alt="Image placeholder">
                                </div>
                                <div class="comment-body">
                                  <h3>John Doe</h3>
                                  <div class="meta">October 03, 2018 at 2:21pm</div>
                                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                  <p><a href="#" class="reply">Reply</a></p>
                                </div>
                              </li>
                            </ul>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </li>

                <li class="comment">
                  <div class="vcard bio">
                    <img src="images/person_1.jpg" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>John Doe</h3>
                    <div class="meta">October 03, 2018 at 2:21pm</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                    <p><a href="#" class="reply">Reply</a></p>
                  </div>
                </li>
              </ul>
              <!-- END comment-list -->
              
              <div class="comment-form-wrap pt-5">
              {% if user.is_authenticated %}
                <h3 class="mb-5">Book Now</h3>
                
                <form action="" method="POST" class="p-5 bg-light">
                    {% csrf_token %}
                    {%bootstrap_form bookingform%}
                    
                  <div class="form-group">
                    <input type="submit" value="Book" class="btn py-3 px-4 btn-primary">
                  </div>
                </form>

                 {% else %}
                <p class="no-comments-allowed">
			            Please <a href="{% url 'login'%}" title="Special:UserLogin">log in</a> to book in this travel</p>
                {% endif %}
              </div>
            </div>

          </div> <!-- .col-md-8 -->
          <div class="col-lg-4 sidebar ftco-animate bg-light py-md-5">
            <div class="sidebar-box ftco-animate">
              <h3>Hot Destinations</h3>
              {% for highly_rated in highly_rated_destinations %}
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url({{highly_rated.image.url}});"></a>
                <div class="text">
                  <h3 class="heading"><a href="{% url 'destination:destination_details' highly_rated.slug %}">{{highly_rated.title}}</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> August 21, 2019</a></div>
                    <div><a href="#"><span class="icon-person"></span> {{highly_rated.company}}</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              {% endfor %}
              
            <div class="sidebar-box ftco-animate">
              <h3>Tag Cloud</h3>
              <div class="tagcloud">
                <a href="#" class="tag-cloud-link">dish</a>
                <a href="#" class="tag-cloud-link">menu</a>
                <a href="#" class="tag-cloud-link">food</a>
                <a href="#" class="tag-cloud-link">sweet</a>
                <a href="#" class="tag-cloud-link">tasty</a>
                <a href="#" class="tag-cloud-link">delicious</a>
                <a href="#" class="tag-cloud-link">desserts</a>
                <a href="#" class="tag-cloud-link">drinks</a>
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Paragraph</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
            </div>
          </div>

        </div>
      </div>
    </section> <!-- .section -->

    
{% endblock %}

destination_app/templates/destination/destinations.html
{%extends "base.html"%}
{%load static%}
{% load countries %}
{% load bootstrap4 %}
{% load custom_tags %}
{%block body%}


<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({%static 'images/bg_1.jpg'%});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1 class="mb-3 bread">Destinations</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="{% url 'destination:destinations'%}">Destinations <i class="ion-ios-arrow-forward"></i></a></span> </p>
          </div>
        </div>
      </div>
    </section>
    <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center pb-4">
          <div class="col-md-12 heading-section text-center ftco-animate">
            <h2 class="mb-4">Best Place Destination</h2>
          </div>
        </div>
        <div class="row">
		{% for top_country in top_countries %}
        	<div class="col-md-3 ftco-animate">
        		<div class="project-destination">
        			<a href="#" class="img" style="background-image: url({% static 'images/destination-9.JPG' %});">
        				<div class="text">
						{% get_countries as countries %}
							{% for country in countries %}						<!--loop in countries till u find our country code then give us its name-->
							{%if top_country.country == country.code %}

        					<h3>{{country.name}} </h3>
							
							{%endif%}
							{% endfor %}

        					<span>{{top_country.qcount}} Tours</span>
        				</div>
        			</a>
        		</div>
        	</div>
		{% endfor %}
        </div>
    	</div>
		
    </section>

    <section class="ftco-section ftco-no-pb ftco-no-pt">
    	<div class="container">
	    	<div class="row">

					<div class="col-md-12 mb-5">
						<div class="search-wrap-1 search-wrap-notop ftco-animate p-4">
							<form action="" method= "GET" class="search-property-1">
		        		<div class="row">
		        			<div class="col-lg align-items-end">
		        				<div class="form-group">
		        					<label for="id_description">Destination</label>
		          				<div class="form-field">
		          					<div class="icon"><span class="ion-ios-search"></span></div>
				                <input type="text" name="description"  class="form-control" placeholder="Search place"> <!-- add name="" for input to run the filter -->
				              </div>
			              </div>
		        			</div>

		        			<div class="col-lg align-items-end">
		        				<div class="form-group is-valid">
		        					<label for="id_check_in_date_0">Check-in-date from</label>
		        					<div class="form-group is-valid">
		          					<div class="icon"><span class="ion-ios-calendar"></span></div>
								  <input type="text" name="check_in_date_after"  class="form-control checkin_date" placeholder="Check in date from" title="" id="id_check_in_date_0"/> 
							  </div>
			              </div>											<!-- check in duration-->
		        			</div>
		        			<div class="col-lg align-items-end">
		        				<div class="form-group">
		        					<label for="id_check_in_date_0">Check-in-date to</label>
		        					<div class="form-field">
		          					<div class="icon"><span class="ion-ios-calendar"></span></div>
				                <input type="text" name="check_in_date_before"  id="id_check_in_date_1" class="form-control checkin_date" placeholder="Check in Date to">
				              </div>
			              </div>
		        			</div>


							<div class="col-lg align-items-end">
		        				<div class="form-group">
		        					<label for="id_price_0">Price Range</label>
		          				<div class="form-field">
		          					<div class="icon"><span class="ion-ios-search"></span></div>
				                <input type="text" name="price_min"  class="form-control" placeholder="Minimum Price" title="" id="id_price_0">
							
				                <input type="text" name="price_max"  class="form-control"  placeholder="Maximaum Price" title="" id="id_price_1">
				              </div>
			              </div>
		        			</div>
		        			<div class="col-lg align-self-end">
		        				<div class="form-group">
		        					<div class="form-field">
				                <input type="submit" value="Search" class="form-control btn btn-primary">
				              </div>
			              </div>
		        			</div>
		        		</div>
		        	</form>
		        </div>
					</div>
	    	</div>
	    </div>
    </section>

    <section class="ftco-section ftco-no-pt">
    	<div class="container">
    		<div class="row justify-content-center pb-4">
          <div class="col-md-12 heading-section text-center ftco-animate">
            <h2 class="mb-4">Tour Destination</h2>
          </div>
        </div>
        <div class="row">
			
				{%for destination in destinations %}
				<div class="col-md-4 ftco-animate">
					<div class="project-wrap">
						<a href="{% url 'destination:destination_details' destination.slug%}" class="img" style="background-image: url({{destination.image.url}});"></a><!-- note that i use .url to show an img from db-->
						<div class="text p-4">
							<span class="price">${{destination.price}}/person</span>
							<span class="days">{{destination.duration}} Days Tour</span>
							<h3><a href="{% url 'destination:destination_details' destination.slug%}">{{destination.title}}</a></h3>


							{% get_countries as countries %}
							{% for country in countries %}						<!--loop in countries till u find our country code then give us its name-->
							{%if destination.country == country.code %}
																										<!--its name-->
							<p class="location"><span class="ion-ios-map"></span> {{destination.city}}, {{ country.name }} <img src="{{destination.country.flag}}" > </p>
																																		<!--show the flag-->
																																		<!--check out settings, base.html, static files(flags),-->			
							{%endif%}
							{% endfor %}


							<ul>
								<li><span class="flaticon-shower"></span>{{destination.bathrooms}}</li>
								<li><span class="flaticon-king-size"></span>{{destination.rooms}}</li>

								{% if destination.distinct_with == "near_mountain" %}			<!--give me the icon according to the choice of "distinct_with" in db-->
								<li><span class="flaticon-mountains"></span>{{destination.distinct_with}}</li>

								{% elif destination.distinct_with == "near_beach" %}
								<li><span class="flaticon-sun-umbrella"></span>{{destination.distinct_with}}</li>
								
								{%endif%}
								
							</ul>
							
						</div>
					</div>
				</div>
			
			{% endfor %}	
			</div>		
		
        
		 {%if destinations.has_other_pages%}

		<div class="row mt-5 mx-auto">
          <div class="col text-center ">
            	<div class="block-27 ">
					<ul>
						{% if destinations.has_previous %}
			    		<li><a href="{% relative_url destinations.previous_page_number 'page' request.GET.urlencode %}">&lt;</a></li>
						{% endif %}

						
                		 {%for i in destinations.paginator.page_range%}
						 			<!--coustm tag to get the current url of the page to paginate filtered results-->	
						 <li><a href="{% relative_url i 'page' request.GET.urlencode %}"><span>{{i}}</span></a></li>
						 {%endfor%}
						

                		{%if destinations.has_next%}
                		<li><a href="{% relative_url destinations.next_page_number 'page' request.GET.urlencode %}">&gt;</a></li>
						{% endif %}
              		</ul>
          		</div>
            </div>
    	</div>
		{% endif %}
    </section>


{%endblock body%}