accounts/urls.py

from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup',views.signup, name='signup'),
    path('profile/<str:user>/',views.profile, name='profile'),   # the user field in Profile model
    path('profile/<str:user>/edit',views.profile_edit, name='profile_edit'),
    
              ]





blog_app/urls.py
from django.urls import path
from . import views



app_name='blog_app'


urlpatterns = [
    path('', views.posts, name='posts'),
    path('post/create/', views.create_post, name='post_create'),
    path('category_posts/<str:slug>', views.category_posts, name='category_posts'),
    path('<str:slug>/', views.PostsDetailsView, name='post_details'),
    path('<str:slug>/update', views.post_update, name='post_update'),
    path('<str:slug>/delete', views.post_delete, name='post_delete'),
    path('<str:slug>/like_or_unlike/', views.like_or_unlike, name='like_or_unlike'),
    path('<str:slug>/<int:id>/comment_update', views.comment_update, name='comment_update'),
    path('<str:slug>/<int:id>/comment_delete', views.comment_delete , name='comment_delete'),
    path('<str:slug>/<int:id>/reply_create'  , views.reply_create , name='reply_create'),
    path('<str:slug>/<int:id>/<int:pk>/reply_to_reply_create'  , views.reply_to_reply_create , name='reply_to_reply_create'),
        #post_deatils #comment #reply
    
    #slug must be the last path in case i have an url matchs with slug the browser will go to the url not the slug
    
    

]

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

destination_app/urls.py
from django.urls import include , path
from . import views

app_name='destination_app'

urlpatterns = [
    path('', views.DestinationsView, name='destinations'),

    path('<str:slug>', views.DestinationDetailsView, name='destination_details'),  #must be the last path in case i have an url matchs with slug the browser will go to the url not the slug
    
    
    


]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')), # to create accounts following my conditions
    path('admin/', admin.site.urls, name='admin'),
    path('destinations/', include('destination_app.urls',namespace='destination')),
    path('blogs/', include('blog_app.urls',namespace='blog')),
    path('martor/', include('martor.urls')),                    # text editor 
    path('oauth/', include('social_django.urls', namespace='social')), # for social login
    path('ratings/', include('star_ratings.urls', namespace='ratings')), # stars rating
    path('chat/', include('chat.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# debug_toolbar settings:

if settings.DEBUG:
    import debug_toolbar
    urlpatterns+= path('__debug__/', include(debug_toolbar.urls)),

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    {% block css1 %}         <!--martor text editor-->
    <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
    <link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
    <link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  {% endblock %}

  {% block css2 %}         <!--star-ratings-->
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
  {% endblock css2 %}

    <title>Vacation - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">

    <link rel="stylesheet" href="{% static "css/aos.css" %}">

    <link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">

    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.timepicker.css" %}">

    
    <link rel="stylesheet" href="{% static "css/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

      
  <link rel="stylesheet" href="{% static 'flags/sprite-hq.css' %}"> <!--check out settings, models, static files(flags), template--> <!-- for countryfield-->


  </head>
  <body>
	  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="index.html">Vacation<span>Travel Agency</span></a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
            
            {% if user.is_authenticated %}
            <li class="nav-item "><a href="{% url 'logout'%}" class="nav-link">Log out</a></li>
            <li class="nav-item "><a href="{% url 'accounts:profile' request.user%}" class="nav-link">My Profile</a></li>
            {% else %}
              
            <li class="nav-item "><a href="{% url 'login'%}" class="nav-link">Login</a></li>
            <li class="nav-item "><a href="{% url 'accounts:signup' %}" class="nav-link">Signup</a></li>
            
            {% endif %}

	          <li class="nav-item"><a href="about.html" class="nav-link">About</a></li>
	          <li class="nav-item active"><a href="{% url 'destination:destinations' %}" class="nav-link">Destinations</a></li>
	          <li class="nav-item"><a href="{% url 'blog:posts' %}" class="nav-link">Blogs</a></li>
	          <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
	          <li class="nav-item cta"><a href="{% url 'destination:destinations' %}" class="nav-link">Book Now</a></li>
            

	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->
    
 

  {%block body%}

  {%endblock body%}


    <footer class="ftco-footer bg-bottom" style="background-image: url({%static 'images/footer-bg.jpg'%});">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Vacation</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Infromation</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Online Enquiry</a></li>
                <li><a href="#" class="py-2 d-block">General Enquiries</a></li>
                <li><a href="#" class="py-2 d-block">Booking Conditions</a></li>
                <li><a href="#" class="py-2 d-block">Privacy and Policy</a></li>
                <li><a href="#" class="py-2 d-block">Refund Policy</a></li>
                <li><a href="#" class="py-2 d-block">Call Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Experience</h2>
              <ul class="list-unstyled">
                  {% if request.user.is_staff %}    <!-- to show to admins only-->
                <li><a href="{% url 'blog:post_create'%}" class="py-2 d-block">Create your blog</a></li>
                  {% endif %}
                <li><a href="#" class="py-2 d-block">Adventure</a></li>
                <li><a href="#" class="py-2 d-block">Hotel and Restaurant</a></li>
                <li><a href="#" class="py-2 d-block">Beach</a></li>
                <li><a href="#" class="py-2 d-block">Camping</a></li>
                <li><a href="#" class="py-2 d-block">Party</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> & <a href="http://www.djangoproject.com/"><img src="https://www.djangoproject.com/m/img/badges/djangopowered126x54.gif" border="0" alt="Powered by Django." title="Powered by Django." /></a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/jquery-migrate-3.0.1.min.js" %}"></script>
  <script src="{% static "js/popper.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/jquery.easing.1.3.js" %}"></script>
  <script src="{% static "js/jquery.waypoints.min.js" %}"></script>
  <script src="{% static "js/jquery.stellar.min.js" %}"></script>
  <script src="{% static "js/owl.carousel.min.js" %}"></script>
  <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
  <script src="{% static "js/aos.js" %}"></script>
  <script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
  <script src="{% static "js/bootstrap-datepicker.js" %}"></script>
  <script src="{% static "js/scrollax.min.js" %}"></script>
  <script src=" https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false" ></script>
  <script src="{% static "js/google-map.js" %}"></script>
  <script src="{% static "js/main.js" %}"></script>
  

{% block js1 %}   <!--martor text editor-->
  <script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/typo.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/spellcheck.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'martor/js/martor.bootstrap.min.js' %}"></script>
{% endblock js1 %}
  
  {% block js2 %}         <!--star-ratings-->
  <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
   {% endblock js2 %} 

  </body>
</html>

templates/base_generic.html


{% load bootstrap4 %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>       
    <title>Vacation - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">

    <link rel="stylesheet" href="{% static "css/aos.css" %}">

    <link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">

    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.timepicker.css" %}">

    
    <link rel="stylesheet" href="{% static "css/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <link rel="stylesheet" href="{% static 'flags/sprite-hq.css' %}"> <!--check out settings, models, static files(flags), template-->

  </head>
  <body>
	  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="index.html">Vacation<span>Travel Agency</span></a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>


	    </div>
	  </nav>
    <!-- END nav -->


    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

              <div class="comment-form-wrap pt-5">
                <form method="POST" class="p-5 bg-light">
                        {%block content%}


                        {%endblock content%}

                </form>
              </div>



    <footer class="ftco-footer bg-bottom" style="background-image: url({%static 'images/footer-bg.jpg'%});">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Vacation</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
 
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/jquery-migrate-3.0.1.min.js" %}"></script>
  <script src="{% static "js/popper.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/jquery.easing.1.3.js" %}"></script>
  <script src="{% static "js/jquery.waypoints.min.js" %}"></script>
  <script src="{% static "js/jquery.stellar.min.js" %}"></script>
  <script src="{% static "js/owl.carousel.min.js" %}"></script>
  <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
  <script src="{% static "js/aos.js" %}"></script>
  <script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
  <script src="{% static "js/bootstrap-datepicker.js" %}"></script>
  <script src="{% static "js/scrollax.min.js" %}"></script>
  <script src=" https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false" ></script>
  <script src="{% static "js/google-map.js" %}"></script>
  <script src="{% static "js/main.js" %}"></script>

  
    
  </body>
</html>

templates/base_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Vacation - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">

    <link rel="stylesheet" href="{% static "css/aos.css" %}">

    <link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">

    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.timepicker.css" %}">

    
    <link rel="stylesheet" href="{% static "css/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <link rel="stylesheet" href="{% static 'flags/sprite-hq.css' %}"> <!--check out settings, models, static files(flags), template-->

  </head>
  <body>
	  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">

	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item active "><a href="{% url 'logout'%}" class="nav-link">Log out</a></li>
            <li class="nav-item active"><a href="{% url 'accounts:profile' request.user %}" class="nav-link">profile</a></li>
            {% else %}
            <li class="nav-item active"><a href="{% url 'login'%}" class="nav-link">Login</a></li>
            <li class="nav-item active"><a href="{% url 'accounts:signup' %}" class="nav-link">Signup</a></li>
            {% endif %}
            <li class="nav-item active"><a href="{% url 'blog:posts' %}" class="nav-link">Blogs</a></li>
	          <li class="nav-item active"><a href="{% url 'destination:destinations' %}" class="nav-link">Destination</a></li>
	          <li class="nav-item cta"><a href="{% url 'destination:destinations' %}" class="nav-link">Book Now</a></li>

	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->
    
 

  {%block body%}

  {%endblock body%}


    <footer class="ftco-footer bg-bottom" style="background-image: url({%static 'images/footer-bg.jpg'%});">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Vacation</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>

          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static "js/jquery.min.js" %}"></script>
  <script src="{% static "js/jquery-migrate-3.0.1.min.js" %}"></script>
  <script src="{% static "js/popper.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
  <script src="{% static "js/jquery.easing.1.3.js" %}"></script>
  <script src="{% static "js/jquery.waypoints.min.js" %}"></script>
  <script src="{% static "js/jquery.stellar.min.js" %}"></script>
  <script src="{% static "js/owl.carousel.min.js" %}"></script>
  <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
  <script src="{% static "js/aos.js" %}"></script>
  <script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
  <script src="{% static "js/bootstrap-datepicker.js" %}"></script>
  <script src="{% static "js/scrollax.min.js" %}"></script>
  <script src=" https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false" ></script>
  <script src="{% static "js/google-map.js" %}"></script>
  <script src="{% static "js/main.js" %}"></script>

  
    
  </body>
</html>