accounts/urls.py

from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup',views.signup, name='signup'),
    path('profile/<str:user>/',views.profile, name='profile'),   # the user field in Profile model
    path('profile/<str:user>/edit',views.profile_edit, name='profile_edit'),
    
              ]





chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')), # to create accounts following my conditions
    path('admin/', admin.site.urls, name='admin'),
    path('destinations/', include('destination_app.urls',namespace='destination')),
    path('blogs/', include('blog_app.urls',namespace='blog')),
    path('martor/', include('martor.urls')),                    # text editor 
    path('oauth/', include('social_django.urls', namespace='social')), # for social login
    path('ratings/', include('star_ratings.urls', namespace='ratings')), # stars rating
    path('chat/', include('chat.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# debug_toolbar settings:

if settings.DEBUG:
    import debug_toolbar
    urlpatterns+= path('__debug__/', include(debug_toolbar.urls)),

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField      # changes in settings

# Create your models here.

class Profile(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE)
    cover_image=models.ImageField(upload_to='profiles/')
    city=models.CharField(max_length=100, null=False, blank=False)
    country = CountryField(null=False , blank=False,               #package
    countries_flag_url='flags/{code}.gif')                         #to show flags #check out settings, base.html, static files(flags), template 
    phone_number=PhoneNumberField(null=False , blank=False)        #package  #check out settings

    
    def __str__(self):
        return self.user.username



@receiver(post_save, sender=User)#SGINAL # to relate between profile & User(built in table)
def create_user_profile(sender, instance, created, **kwargs):  #create user when i create profile
    if created:
        Profile.objects.create(user=instance)






accounts/views.py
from django.shortcuts import redirect, render
from . form import *
from django.contrib.auth import authenticate, login
from accounts.models import Profile
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.


def signup(request):
    if request.method=="POST":
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save()  #to log in automaticly after signing up 
            username= form.cleaned_data['username']
            password= form.cleaned_data['password1']
            user= authenticate(username=username, password=password)
            login(request,user)
            return redirect(reverse('accounts:profile', args=(user,)))

    else:
        form = SignupForm()

    return render(request, 'registration/signup.html',{'form':form})  



def profile(request,user):
    the_user= User.objects.get(username=user)
    profile= Profile.objects.get(user=the_user)
    return render(request, 'profiles/profile.html',{'profile': profile})



@login_required
def profile_edit(request,user):
    profile= Profile.objects.get(user=request.user)

    if request.method=='POST':
        userform=UserForm(request.POST,instance=request.user)
        profileform= ProfileForm(request.POST, request.FILES, instance=profile )
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile= profileform.save(commit=False)
            myprofile.save()
            return redirect(reverse('accounts:profile', args=(user,)))

                                      #to give the page the logged in user data 
    else:                             #↑
        userform = UserForm(instance=request.user)     
        profileform = ProfileForm(instance=profile)


    return render(request,'profiles/profile_edit.html',{'userform': userform ,'profileform':profileform, 'profile' : profile})











accounts/templates/profiles/profile.html

{% extends 'base_profile.html'%}
{% load bootstrap4 %}

{%block body%}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Welcome in {{profile}}'s profile</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">

                <div class="col-lg-8" mx-auto>
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h4>profile Summery</h4>
                        </div>
                        <div class="job_content">
                            <ul>                  <!--information from models-->  
                                <li>name : <span>{{profile}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>     <!--email is from  django created table users not from  my created profile table-->
                                <li>phone: <span>{{profile.phone_number}}</span></li>
                                <li>Address: <span>{{profile.city}}</span></li>
                            
                                {% ifequal profile.user request.user %} 
                                <a class="boxed-btn3 w-100"  href="{% url 'accounts:profile_edit' request.user %}">Edit profile</a>
                                {% endifequal %}
                            </ul>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>

{%endblock body%}

accounts/templates/profiles/profile_edit.html

{% extends 'base_profile.html'%}
{% load bootstrap4 %}

{%block body%}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>edit {{profile}} profile</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userform%}
                            {% bootstrap_form profileform %}
                            {% buttons %}
                            <button class="boxed-btn3 w-100" type="submit">edit profile</button>
                            {% endbuttons %}
                            
                            <p><a href="{% url 'password_change' %}">change your password</a></p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{%endblock body%}